[tool.poetry]
name = "bible-verses-bot"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.10"
beautifulsoup4 = "^4.12.2"
Flask = "^2.3.2"
httpx = "^0.24.1"
lxml = "^4.9.3"
pyTelegramBotAPI = "^4.12.0"
typing-extensions = "^4.7.1"
firebase-admin = "^6.2.0"
Cython = "^0.29.36"
waitress = "^2.1.2"

[tool.poetry.dev-dependencies]
urllib3 = "1.26.16"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
