[tool.poetry]
name = "bible-verses-bot-v8"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
beautifulsoup4 = "^4.10.0"
Flask = "^2.0.2"
httpx = "^0.22.0"
lxml = "^4.7.1"
pyTelegramBotAPI = "^4.7.0"
typing-extensions = "^4.3.0"
firebase-admin = "^5.3.0"
Cython = "^0.29.33"

[tool.poetry.dev-dependencies]
Cython = "^0.29.32"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
