# yaml-language-server: $schema=https://render.com/schema/render.yaml.json

services:
  - type: web
    name: Bible Verses Bot
    region: singapore
    plan: free
    branch: master
    autoDeploy: true
    runtime: python
    buildCommand: >
      pip install pdm
      && python -m pdm install
      && python setup.py build_ext --inplace
    startCommand: python main.py
    healthCheckPath: /
    envVars:
      - key: API_KEY
        sync: false
      - key: DEV_ID
        sync: false
      - key: FIREBASE_AUTH_PROVIDER_X509_CERT_URL
        sync: false
      - key: FIREBASE_AUTH_URI
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_CLIENT_ID
        sync: false
      - key: FIREBASE_CLIENT_X509_CERT_URL
        sync: false
      - key: FIREBASE_DB_URL
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: FIREBASE_PRIVATE_KEY_ID
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_TOKEN_URI
        sync: false
      - key: FIREBASE_TYPE
        sync: false
      - key: PORT
        value: 8080
      - key: POETRY_VERSION
        value: 1.8.4
      - key: PYTHON_VERSION
        value: 3.12.7
